---
- name: Update splunk cloud index | {{ splunk_cloud_index_config.name }}
  ansible.builtin.uri:
    url: "https://{{ splunk_acs_domain }}/{{ splunk_cloud_stack }}/adminconfig/v2/indexes/{{ splunk_cloud_index_config.name }}"
    method: PATCH
    body_format: json
    status_code: [200, 202]
    return_content: true
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ splunk_cloud_token }}"
    body: >-
      {{
        {
          "maxDataSizeMB": splunk_cloud_index_config.maxDataSizeMB | int,
          "searchableDays": splunk_cloud_index_config.searchableDays | int
        } 
        | combine({"selfStorageBucketPath": splunk_cloud_index_config.selfStorageBucketPath} 
          if splunk_cloud_index_config.selfStorageBucketPath is defined and splunk_cloud_index_config.selfStorageBucketPath | length > 0 else {})
      }}
  timeout: 90
  retries: 3
  changed_when: true
  register: r_update_index
  tags:
    - splunk_cloud_update_index
