---
- name: List all Splunk Cloud users
  ansible.builtin.uri:
    url: "https://{{ splunk_acs_domain }}/{{ splunk_cloud_stack }}/adminconfig/v2/users"
    method: GET
    status_code: [200]
    return_content: true
    headers:
      Authorization: "Bearer {{ splunk_cloud_token }}"
  register: r_splunk_cloud_users

- name: Manage users
  ansible.builtin.include_tasks: user_loop.yml
  loop: "{{ splunk_cloud_user_list }}"
  loop_control:
    loop_var: "user" 