---
splunkbase_app_list:
  - id: 2968 # SA-cim_vladiator
    version: "1.8.2"
    license: "https://www.apache.org/licenses/LICENSE-2.0.html"
    permissions:
      sharing: "global"
      read: "*"
      write: "sc_admin,power"

  # Splunk Machine Learning Toolkit
  - id: 2890
    version: "5.4.1"
    license: "https://www.splunk.com/en_us/legal/splunk-general-terms.html"
    permissions:
      sharing: "global"
      read: "*"
      write: "sc_admin"

  # Splunk App for Lookup File Editing
  - id: 1724
    version: "4.0.2"
    license: "https://www.splunk.com/en_us/legal/splunk-general-terms.html"
    permissions:
      sharing: "global"
      read: "*"
      write: "sc_admin"

  # Splunk Common Information Model (CIM)
  - id: 1621
    version: "5.3.1"
    license: "https://www.splunk.com/en_us/legal/splunk-general-terms.html"
    permissions:
      sharing: "global"
      read: "*"
      write: "sc_admin"
