splunk_cloud_role_list:
  - name: example_role
    capabilities: [list_all_objects]
    state: present
  - name: example_role2
    capabilities: [admin_all_objects]
    state: present

  # Create our demo role definition
  - name: demo_role
    state: present
    capabilities: []
    srchIndexesAllowed: [
      "main",
      "common_aws",
      "common_azure",
      "_internal"
    ]
    srchIndexesDefault: [
      "main"
    ]
    cumulativeRTSrchJobsQuota: 100
    cumulativeSrchJobsQuota: 50
    defaultApp: "search"
    importedRoles: [power]
    rtSrchJobsQuota: 6
    srchDiskQuota: 1000
    srchFilter: ""
    srchJobsQuota: 3
    srchTimeEarliest: 0
    srchTimeWin: -1
