---
galaxy_info:
  author: Will Searle
  description: Manage limits.conf configurations in Splunk Cloud Platform
  company: LiveHybrid Ltd
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - splunk
    - cloud
    - limits
    - configuration
dependencies: []