name: Execute ansible playbook
on:
  workflow_call:
    inputs:
      ansible_inventory:
        required: true
        type: string
      ansible_playbook:
        required: true
        type: string
      ansible_extra_args:
        required: false
        type: string
        default: ""
    secrets:
      ANSIBLE_VAULT_PASSWORD:
        required: false
      SPLUNKBASE_USERNAME:
        required: false
      SPLUNKBASE_PASSWORD:
        required: false
      SPLUNK_TOKEN:
        required: false
      SPLUNKCLOUD_STACK:
        required: false
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: "pip"
      - name: "install ansible"
        run: pip install -r requirements.txt

      - name: "run playbook"
        run: |
          echo '${{ github.workflow }}'
          echo '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > vault.txt
          SPLUNK_TOKEN=${{ secrets.SPLUNK_TOKEN }} \
          SPLUNKBASE_USERNAME=${{ secrets.SPLUNKBASE_USERNAME }} \
          SPLUNKBASE_PASSWORD=${{ secrets.SPLUNKBASE_PASSWORD }} \
          ansible-playbook -i ${{ inputs.ansible_inventory }}  -e "splunk_cloud_stack=${{ secrets.SPLUNKCLOUD_STACK }}" --vault-pass-file vault.txt ${{ inputs.ansible_playbook }} ${{ inputs.ansible_extra_args }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
      - name: Save Private app inspection reports
        uses: actions/upload-artifact@v4
        with:
          name: appinspect-report
          path: reports/
        if: github.workflow == 'deploy private apps'
