name: deploy hec token
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "inventory/host_vars/*/hec_token.yml"

concurrency:
  group: ${{ github.workflow }}

jobs:
  ansible:
    name: deploy hec token
    uses: ./.github/workflows/ansible-playbook.yml
    with:
      ansible_playbook: cloud_hec_token_config.yml
      ansible_inventory: inventory
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SPLUNKBASE_USERNAME: ${{ secrets.SPLUNKBASE_USERNAME }}
      SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
      SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
      SPLUNKCLOUD_STACK: ${{ secrets.SPLUNKCLOUD_STACK }} 