name: deploy restart
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  ansible:
    name: deploy restart
    uses: ./.github/workflows/ansible-playbook.yml
    with:
      ansible_playbook: cloud_restart.yml
      ansible_inventory: inventory
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SPLUNKBASE_USERNAME: ${{ secrets.SPLUNKBASE_USERNAME }}
      SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
      SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
      SPLUNKCLOUD_STACK: ${{ secrets.SPLUNKCLOUD_STACK }} 