name: deploy maintenance window
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "inventory/host_vars/*/maintenance_window.yml"

concurrency:
  group: ${{ github.workflow }}

jobs:
  ansible:
    name: deploy maintenance window
    uses: ./.github/workflows/ansible-playbook.yml
    with:
      ansible_playbook: cloud_maintenance_window.yml
      ansible_inventory: inventory
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SPLUNKBASE_USERNAME: ${{ secrets.SPLUNKBASE_USERNAME }}
      SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
      SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
      SPLUNKCLOUD_STACK: ${{ secrets.SPLUNKCLOUD_STACK }} 